version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hosiktamtam-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin12345
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-time-zone=Asia/Seoul
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: